"""On-premises operational database contracts and deployment helpers."""

from pharmstock.onprem.contracts import (
    CDC_PLUGIN,
    CDC_POST_STAGE7E_TABLES,
    CDC_PUBLICATION,
    CDC_SLOT,
    CDC_STAGE7D_TABLES,
    CDC_TABLES,
    CDC_TOPIC_PREFIX,
    DEBEZIUM_COMPATIBLE_RELEASE,
    ONPREM_SCHEMAS,
    POSTGRES_ADMIN_USER,
    POSTGRES_APP_USER,
    POSTGRES_CDC_USER,
    POSTGRES_DATABASE,
    POSTGRES_HOST_PORT,
    POSTGRES_IMAGE,
    SEED_CONTRACTS,
    OnPremContractError,
    assert_stage_success,
    database_contract,
    input_row_counts,
    write_database_contract,
)

__all__ = [
    "CDC_PLUGIN",
    "CDC_PUBLICATION",
    "CDC_SLOT",
    "CDC_POST_STAGE7E_TABLES",
    "CDC_STAGE7D_TABLES",
    "CDC_TABLES",
    "CDC_TOPIC_PREFIX",
    "DEBEZIUM_COMPATIBLE_RELEASE",
    "ONPREM_SCHEMAS",
    "POSTGRES_ADMIN_USER",
    "POSTGRES_APP_USER",
    "POSTGRES_CDC_USER",
    "POSTGRES_DATABASE",
    "POSTGRES_HOST_PORT",
    "POSTGRES_IMAGE",
    "SEED_CONTRACTS",
    "OnPremContractError",
    "assert_stage_success",
    "database_contract",
    "input_row_counts",
    "write_database_contract",
]
