"""Visible FEFO demo using batch CSV files generated by Stage 2D."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from datetime import date
from pathlib import Path
from uuid import UUID

from pharmstock.domain import InventoryBatch, consume_fefo


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Demonstrate FEFO from generated batch files")
    parser.add_argument("--batch-dir", type=Path, default=Path("artifacts/stage2d/batches"))
    parser.add_argument("--as-of", type=date.fromisoformat, default=date(2026, 8, 22))
    return parser.parse_args()


def load_example(batch_dir: Path, as_of: date) -> tuple[InventoryBatch, ...]:
    grouped: dict[tuple[str, str], list[InventoryBatch]] = defaultdict(list)
    for path in sorted(batch_dir.glob("part-*.csv")):
        with path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.DictReader(handle):
                batch = InventoryBatch(
                    batch_id=UUID(row["batch_id"]),
                    branch_id=UUID(row["branch_id"]),
                    product_id=UUID(row["product_id"]),
                    batch_number=row["batch_number"],
                    received_on=date.fromisoformat(row["received_on"]),
                    expires_on=date.fromisoformat(row["expires_on"]),
                    on_hand_quantity=int(row["on_hand_quantity"]),
                )
                key = (row["branch_id"], row["product_id"])
                grouped[key].append(batch)
                usable = sorted(
                    [
                        b
                        for b in grouped[key]
                        if not b.is_expired(as_of=as_of) and b.on_hand_quantity > 0
                    ],
                    key=lambda b: (b.expires_on, b.received_on, b.batch_number),
                )
                if len(usable) >= 2:
                    return tuple(grouped[key])
    raise RuntimeError("no multi-batch branch/product example found")


def main() -> int:
    args = parse_args()
    if not args.batch_dir.exists():
        print(f"STAGE_2D_FEFO_STATUS=FAIL\nBatch directory not found: {args.batch_dir}")
        print("Run scripts/run_stage2d_scale.py first.")
        return 2

    batches = load_example(args.batch_dir, args.as_of)
    usable = sorted(
        [batch for batch in batches if not batch.is_expired(as_of=args.as_of)],
        key=lambda batch: (batch.expires_on, batch.received_on, batch.batch_number),
    )
    quantity = usable[0].on_hand_quantity + 1
    result = consume_fefo(batches=batches, quantity=quantity, as_of=args.as_of)

    print("=== PharmStock V2 / Stage 2D FEFO ===")
    print(f"Branch ID:          {result.branch_id}")
    print(f"Product ID:         {result.product_id}")
    print(f"As of:              {args.as_of.isoformat()}")
    print(f"Requested quantity: {quantity}")
    print("\nUsable batches before sale (expiry order):")
    for batch in usable:
        print(
            f"  {batch.batch_number} | expiry={batch.expires_on.isoformat()} | "
            f"qty={batch.on_hand_quantity:,}"
        )

    print("\nFEFO allocations:")
    for allocation in result.allocations:
        print(
            f"  TAKE {allocation.quantity:,} from {allocation.batch_number} "
            f"(expiry {allocation.expires_on.isoformat()})"
        )

    after = {batch.batch_id: batch for batch in result.updated_batches}
    print("\nRemaining quantities:")
    for batch in usable:
        print(f"  {batch.batch_number}: {after[batch.batch_id].on_hand_quantity:,}")
    print("\nSTAGE_2D_FEFO_STATUS=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
